source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

workspace 'SSStorageNodeDemo'
project 'SSStorageNodeDemo'

target 'SSStorageNodeDemo' do
    pod 'SSStorageNode', :path => '../../SSStorageNode'
end
