source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

workspace 'SSStorageNodeDemo'
project 'SSStorageNodeDemo'

target 'SSStorageNodeDemo' do
#    pod 'SSStorageNode', :git => 'git@github.com:kingundertree/SSStorageNode.git', :tag => '0.0.1'

    pod 'SSStorageNode', :path => '../../SSStorageNode'
end
